#include "crash_dump.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <string>
#include <algorithm>

#include "esp_core_dump.h"
#include "esp_partition.h"
#include "esp_random.h"

#include "ClassLogFile.h"
#include "Helper.h"
#include "time_sntp.h"

// Defined in the autogenerated version.cpp. Declared here (not via version.h, which carries inline
// function definitions that would double-define if included from a second translation unit).
extern "C"
{
    extern const char *GIT_REV;
    extern const char *GIT_BRANCH;
    extern const char *BUILD_TIME;
}

static const char *TAG = "CRASHDUMP";

#define CRASH_DIR "/sdcard/log/crash"

void saveCoreDumpToSD(void)
{
    // Nothing stored (normal boot) -> no-op. Also covers builds/targets without a valid image.
    if (esp_core_dump_image_check() != ESP_OK) {
        return;
    }

    LogFile.WriteToFile(ESP_LOG_WARN, TAG, "A coredump is stored in flash - extracting it to the SD card...");
    MakeDir(CRASH_DIR);

    // Unique base name. The RTC clock usually survives a panic reboot, so a timestamp is meaningful;
    // a short random suffix avoids collisions if two crashes land in the same second.
    std::string ts = getCurrentTimeString("%Y-%m-%d_%H-%M-%S");
    char suffix[8];
    snprintf(suffix, sizeof(suffix), "_%04x", (unsigned)(esp_random() & 0xFFFF));
    std::string base = std::string(CRASH_DIR) + "/crash_" + ts + suffix;

    // 1) Human-readable summary: faulting task, exception PC and the call backtrace. Enough to
    //    addr2line against the matching firmware.elf without needing the full ELF.
    esp_core_dump_summary_t *summary = (esp_core_dump_summary_t *) calloc(1, sizeof(esp_core_dump_summary_t));
    if (summary != NULL) {
        if (esp_core_dump_get_summary(summary) == ESP_OK) {
            FILE *f = fopen((base + ".txt").c_str(), "w");
            if (f != NULL) {
                fprintf(f, "AI-on-the-edge crash report\n");
                fprintf(f, "===========================\n");
                fprintf(f, "Firmware     : %s (%s)\n", GIT_BRANCH ? GIT_BRANCH : "?", GIT_REV ? GIT_REV : "?");
                fprintf(f, "Build time   : %s\n", BUILD_TIME ? BUILD_TIME : "?");
                fprintf(f, "Reset reason : %s\n", getResetReason().c_str());
                fprintf(f, "Faulting task: %s\n", summary->exc_task);
                fprintf(f, "Exception PC : 0x%08x\n", (unsigned) summary->exc_pc);
#if __XTENSA__
                fprintf(f, "Backtrace (%u frame(s)%s):\n", (unsigned) summary->exc_bt_info.depth,
                        summary->exc_bt_info.corrupted ? " - CORRUPTED" : "");
                for (uint32_t i = 0; i < summary->exc_bt_info.depth; ++i) {
                    fprintf(f, "  #%02u 0x%08x\n", (unsigned) i, (unsigned) summary->exc_bt_info.bt[i]);
                }
#endif
                fprintf(f, "\nFull analysis: espcoredump.py info_corefile -c %s.elf <firmware.elf>\n", base.c_str());
                fclose(f);
                LogFile.WriteToFile(ESP_LOG_WARN, TAG, "Crash summary -> " + base + ".txt");
            }
        }
        free(summary);
    }

    // 2) Raw ELF image, copied straight out of the coredump partition for full offline analysis.
    size_t addr = 0, size = 0;
    if (esp_core_dump_image_get(&addr, &size) == ESP_OK && size > 0) {
        const esp_partition_t *part = esp_partition_find_first(
            ESP_PARTITION_TYPE_DATA, ESP_PARTITION_SUBTYPE_DATA_COREDUMP, NULL);
        if (part != NULL) {
            FILE *f = fopen((base + ".elf").c_str(), "wb");
            if (f != NULL) {
                uint8_t buf[1024];
                size_t off = 0;
                bool ok = true;
                while (off < size) {
                    size_t chunk = std::min((size_t) sizeof(buf), size - off);
                    if (esp_partition_read(part, off, buf, chunk) != ESP_OK) {
                        ok = false;
                        break;
                    }
                    fwrite(buf, 1, chunk, f);
                    off += chunk;
                }
                fclose(f);
                LogFile.WriteToFile(ok ? ESP_LOG_WARN : ESP_LOG_ERROR, TAG,
                    ok ? ("Crash ELF -> " + base + ".elf (" + std::to_string(size) + " bytes)")
                       : ("Crash ELF copy failed (partition read error) -> " + base + ".elf"));
            }
        }
    }

    // 3) Erase the stored dump so it is not re-extracted on every subsequent boot.
    if (esp_core_dump_image_erase() == ESP_OK) {
        LogFile.WriteToFile(ESP_LOG_INFO, TAG, "Coredump erased from flash after saving to SD");
    }

    LogFile.WriteToFile(ESP_LOG_WARN, TAG, "Crash dump saved under " CRASH_DIR " - retrieve it via the web fileserver");
}
